# PPO configs
PPO_N_EPOCHS = 5
PPO_LEARNING_RATE_START = 3e-4
PPO_LEARNING_RATE_END = 1e-5
PPO_BATCH_SIZE = 2**8
PPO_GAMMA = 0.99
PPO_N_STEPS = 2**12  # Rollout buffer size per environment
PPO_N_ENVS = 10
PPO_ENT_COEF = 0.005
PPO_VF_COEF = 0.5
PPO_TARGET_KL = 100
PPO_MAX_GRAD_NORM = 0.5
PPO_GAE_LAMBDA = 0.95
PPO_CLIP_RANGE = 0.3
PPO_TOTAL_TIMESTEPS = 500 * PPO_N_STEPS * PPO_N_ENVS
