import torch

# PPO configs
PPO_N_EPOCHS = 10
PPO_LEARNING_RATE_START = 1e-4
PPO_LEARNING_RATE_END = 1e-5
PPO_BATCH_SIZE = 2**12
PPO_MINIBATCH_SIZE = 2**7
PPO_GAMMA = 0.99
PPO_N_STEPS = 2**11  # Rollout buffer size per environment
PPO_N_ENVS = 2**1
PPO_ENT_COEF = 0.005
PPO_VF_COEF = 0.5
PPO_TARGET_KL = None    # 0.02
PPO_MAX_GRAD_NORM = 0.5
PPO_GAE_LAMBDA = 0.95
PPO_CLIP_RANGE = 0.2  # 0.1
PPO_TOTAL_TIMESTEPS = 1000 * PPO_N_STEPS * PPO_N_ENVS
PPO_IMAGE_SIZE = (64, 64)
PPO_FRAMES_PER_BATCH = PPO_N_STEPS * PPO_N_ENVS
